In [2]:
# PANDAS LIBRARY INTRODUCTION 
# introduction to pandas library
# works of pandas is : 
#     Data Analysis and Data Manipulation,
#     Collect and Transform Data
#     Reshaping of Data Sets 
#     Time series-specific Functionality
#     Converting Other data structures into DataFrame 

In [3]:
# SERIES STRUCTURE IN PANDAS LIBRARY
# Creating a Pandas Series with a List 
# the Pandas series; was created based on NumPy arrays 
# Pandas series keeps index information for each value as an extra.

In [4]:
import pandas as pd

In [14]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [20]:
list_data=[2,4,6,8,10]
list_index=["a","b","c","d","e"]

In [29]:
variable=pd.Series(data=list_data,index=list_index,dtype="float16")

In [30]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float16

In [31]:
type(variable)

pandas.core.series.Series

In [39]:
list_data=[2,4,6,8,10,12]
list_index=["a","b","c","d","e"]

In [37]:
pd.Series(list_data,list_index)

ValueError: Length of values (5) does not match length of index (6)

In [40]:
# 2. Creating a Pandas Series with a Dictionary
import pandas as pd

In [43]:
dictionary={"ferrari":334.7,"porche":337.9,"lamborghini":349}

In [52]:
for carSpeed,speed in dictionary.items():
    print(carSpeed,speed)

ferrari 334.7
porche 337.9
lamborghini 349


In [45]:
pd.Series(data=dictionary)

ferrari        334.7
porche         337.9
lamborghini    349.0
dtype: float64

In [54]:
pd.Series(data=dictionary,index=["porche","bugatti","ferrari"])

porche     337.9
bugatti      NaN
ferrari    334.7
dtype: float64

In [56]:
# 3. Creating Pandas Series with NumPy Array
import numpy as np
import pandas as pd

In [58]:
example=np.array([1,3.3,5,7.2,9])
labels=np.array(["a","b","c","d","e"])

In [60]:
numpyArrVariable=pd.Series(data=example,index=labels)

In [61]:
numpyArrVariable

a    1.0
b    3.3
c    5.0
d    7.2
e    9.0
dtype: float64

In [62]:
# 4. Object types in Series 
import pandas as pd

In [64]:
example=pd.Series(["world",100,5.8,False])

In [65]:
example

0    world
1      100
2      5.8
3    False
dtype: object

In [70]:
print(type(example[0]))
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [79]:
pd.Series([sum,type,max])

0    <built-in function sum>
1             <class 'type'>
2    <built-in function max>
dtype: object

In [80]:
# 5. Examining the Primary Features of the Pandas Seri
import pandas as pd

In [81]:
example=pd.Series([10,20,30,40,50,60,70])

In [82]:
example

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [84]:
example.axes

[RangeIndex(start=0, stop=7, step=1)]

In [85]:
example.dtype

dtype('int64')

In [87]:
example.ndim

1

In [94]:
example.head(4) # head method return first five values by default

0    10
1    20
2    30
3    40
dtype: int64

In [96]:
example.tail(3)

4    50
5    60
6    70
dtype: int64

In [97]:
# 6. Most Applied Methods on Pandas Series
import pandas as pd

In [103]:
variable2=pd.Series([8,3,6,5,1],index=["a","b","c","d","e"])

In [104]:
variable2

a    8
b    3
c    6
d    5
e    1
dtype: int64

In [105]:
new_variable=variable2.sort_index()

In [106]:
new_variable

a    8
b    3
c    6
d    5
e    1
dtype: int64

In [112]:
new_variable2=variable2.sort_values()

In [113]:
new_variable2

e    1
b    3
d    5
c    6
a    8
dtype: int64

In [115]:
variable2.isin([6,1])

a    False
b    False
c     True
d    False
e     True
dtype: bool

In [116]:
variable2[variable2.isin([6,1])]

c    6
e    1
dtype: int64

In [119]:
variable2.values

array([8, 3, 6, 5, 1], dtype=int64)

In [120]:
variable2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [122]:
[i for i in variable2.values]

[8, 3, 6, 5, 1]

In [123]:
variable2.items

<bound method Series.items of a    8
b    3
c    6
d    5
e    1
dtype: int64>

In [124]:
variable2.items()

In [125]:
list(variable2.items())

[('a', 8), ('b', 3), ('c', 6), ('d', 5), ('e', 1)]

In [130]:
for index,value in variable2.items():
    print(index, '-', value)

a - 8
b - 3
c - 6
d - 5
e - 1


In [131]:
# 7. Indexing and Slicing Pandas Series
import pandas as pd

In [132]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [133]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [135]:
example[2:6]

France    +33
Italy     +39
Sweden    +46
Norway    +47
dtype: object

In [137]:
example[0::2]

Turkey    +90
France    +33
Sweden    +46
dtype: object

In [138]:
example["Germany"]

'+49'

In [144]:
example["France":"Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [ ]:
# 9. DataFrame Structures in Pandas Library
# 1. Creating Pandas DataFrame with List 
# Pandas Dataframe is a multidimensional data structure 

In [145]:
import pandas as pd

In [155]:
list_example=[5,10,15,20,25]

In [156]:
pd.DataFrame(data=list_example,columns=["values"],dtype="float")

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

In [ ]:
# 2. Creating Pandas DataFrame with NumPy Array

In [158]:
import numpy as np
import pandas as pd

In [159]:
array_example=np.random.randint(0,50,(4,4))

In [160]:
array_example

array([[33, 22, 43, 32],
       [39, 28, 39, 31],
       [29, 17,  5, 41],
       [46,  3, 37,  7]])

In [164]:
df=pd.DataFrame(array_example,index=["row1","row2","row3","row4"],columns=["col1","col2","col3","col4"])

In [165]:
df

col1  col2  col3  col4
row1    33    22    43    32
row2    39    28    39    31
row3    29    17     5    41
row4    46     3    37     7

In [166]:
# 3. Creating Pandas DataFrame with Dictionary 
import numpy as np
import pandas as pd

In [179]:
x=np.random.randint(10,50,size=6)
y=np.random.randint(10,50,size=6)
z=np.random.randint(10,50,size=6)
t=np.random.randint(10,50,size=6)

In [174]:
x

array([29, 12, 20, 44, 40, 34])

In [175]:
y

array([24, 35, 22, 30, 33, 39])

In [176]:
z

array([31, 49, 49, 27, 48, 42])

In [185]:
dict_example={"val1":x,"val2":y,"val3":z,"val4":t}

In [186]:
dict_example

{'val1': array([33, 43, 38, 15, 45, 10]),
 'val2': array([14, 26, 21, 15, 15, 25]),
 'val3': array([49, 28, 16, 12, 23, 17]),
 'val4': array([28, 45, 37, 36, 45, 15])}

In [187]:
df=pd.DataFrame(dict_example)

In [188]:
df

val1  val2  val3  val4
0    33    14    49    28
1    43    26    28    45
2    38    21    16    37
3    15    15    12    36
4    45    15    23    45
5    10    25    17    15

In [7]:
# 4. Examining the Properties of Pandas DataFrames
import numpy as np
import pandas as pd
x1=np.random.randint(10,50,size=6)
y1=np.random.randint(10,50,size=6)
z1=np.random.randint(10,50,size=6)
t1=np.random.randint(10,50,size=6)

In [12]:
dict_example2={"val1":x1,"val2":y1,"val3":z1,"val4":t1}

In [14]:
df1=pd.DataFrame(dict_example2)

In [15]:
df1.head() # it gives df variable DataFrame first five values by default 

val1  val2  val3  val4
0    17    36    49    13
1    36    22    16    49
2    31    14    15    44
3    31    31    35    33
4    34    41    19    11

In [16]:
df1.head(3)

val1  val2  val3  val4
0    17    36    49    13
1    36    22    16    49
2    31    14    15    44

In [17]:
df1.tail(3) # gives last three dataFrames rows 

val1  val2  val3  val4
3    31    31    35    33
4    34    41    19    11
5    32    20    29    43

In [18]:
df1.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [19]:
[i for i in df1.columns]

['val1', 'val2', 'val3', 'val4']

In [20]:
df1.columns=["new1","new2","new3","new4"]

In [21]:
df1

new1  new2  new3  new4
0    17    36    49    13
1    36    22    16    49
2    31    14    15    44
3    31    31    35    33
4    34    41    19    11
5    32    20    29    43

In [22]:
df1.values

array([[17, 36, 49, 13],
       [36, 22, 16, 49],
       [31, 14, 15, 44],
       [31, 31, 35, 33],
       [34, 41, 19, 11],
       [32, 20, 29, 43]])

In [23]:
type(df1.values)

numpy.ndarray

In [24]:
type(df1)

pandas.core.frame.DataFrame

In [25]:
df1.describe()

new1       new2       new3       new4
count   6.000000   6.000000   6.000000   6.000000
mean   30.166667  27.333333  27.166667  32.166667
std     6.735478  10.347302  13.272779  16.473211
min    17.000000  14.000000  15.000000  11.000000
25%    31.000000  20.500000  16.750000  18.000000
50%    31.500000  26.500000  24.000000  38.000000
75%    33.500000  34.750000  33.500000  43.750000
max    36.000000  41.000000  49.000000  49.000000

In [26]:
df1.ndim

2

In [28]:
df1.size

24

In [29]:
# ELEMENT SELECTION OPERATIONS IN DATAFRAME STRUCTURES

In [1]:
# 1. Element Selection Operations in Pandas DataFrames Lesson 1 
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)
df=pd.DataFrame(data=np.random.randn(6,5),index="A B C D E F".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [3]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [10]:
df["VAL1"]

VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [15]:
df["VAL1"][0:3]

VAL1
A  2.706850
B -0.319318
C  0.528813

In [17]:
df[["VAL1"]][0:3]

VAL1
A  2.706850
B -0.319318
C  0.528813

In [23]:
df[["VAL1","VAL2"]][0:3]

VAL1      VAL2
A  2.706850  0.628133
B -0.319318 -0.848077
C  0.528813 -0.589001

In [28]:
df[["VAL1","VAL2"]]["B":"D"]

VAL1      VAL2
B -0.319318 -0.848077
C  0.528813 -0.589001
D  0.955057  0.190794

In [7]:
df.VAL1

VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [8]:
df.VAL3

VAL3
A  0.907969
B  0.605965
C  0.188695
D  1.978757
E -1.706086
F  0.184502

In [9]:
df["VAL1"].values

array([[ 2.70684984],
       [-0.31931804],
       [ 0.52881349],
       [ 0.95505651],
       [ 0.30266545],
       [ 0.39052784]])

In [80]:
df[["VAL1"]]

VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [81]:
df[["VAL1"]]["B":"D"]

VAL1
B -0.319318
C  0.528813
D  0.955057

In [82]:
df[["VAL1"]][1:4]

VAL1
B -0.319318
C  0.528813
D  0.955057

In [84]:
df["VAL1"][1:4]

VAL1
B -0.319318
C  0.528813
D  0.955057

In [37]:
# 2. Element Selection Operations in Pandas DataFrames Lesson 2
import numpy as np
import pandas as pd

In [38]:
np.random.seed(101)
df=pd.DataFrame(data=np.random.randn(6,5),index="A B C D E F".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [39]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [40]:
df[["VAL2","VAL5"]]

VAL2      VAL5
A  0.628133  0.651118
B -0.848077  0.740122
C -0.589001 -0.933237
D  0.190794  0.683509
E  1.693723 -0.134841
F  0.166905  0.072960

In [44]:
df[["VAL2","VAL2"]]

VAL2      VAL2
A  0.628133  0.628133
B -0.848077 -0.848077
C -0.589001 -0.589001
D  0.190794  0.190794
E  1.693723  1.693723
F  0.166905  0.166905

In [45]:
df[["VAL2","VAL5"]]

VAL2      VAL5
A  0.628133  0.651118
B -0.848077  0.740122
C -0.589001 -0.933237
D  0.190794  0.683509
E  1.693723 -0.134841
F  0.166905  0.072960

In [46]:
newSeries=df["VAL1"]

In [48]:
type(newSeries)

pandas.core.frame.DataFrame

In [49]:
newSeries2=df[["VAL1"]]

In [53]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [55]:
# How can we get dataframee on rows bases 
df["B":"D"]

VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [56]:
df[1:4]

VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [62]:
df["E":"E"]

VAL1      VAL2      VAL3      VAL4      VAL5
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [68]:
df["E":"E"][["VAL2","VAL5"]]

VAL2      VAL5
E  1.693723 -0.134841

In [77]:
# 3. Top Level Element Selection in Pandas DataFramesLesson 1
# Structure of loc and iloc 
import numpy as np
import pandas as pd

In [80]:
np.random.seed(101)
array=np.random.randint(10,50,(10,5))
df=pd.DataFrame(data=array,index="A B C D E F G H I J".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [81]:
array

array([[41, 21, 27, 16, 33],
       [21, 19, 23, 14, 38],
       [10, 15, 22, 39, 29],
       [18, 39, 44, 18, 29],
       [20, 22, 41, 33, 10],
       [19, 18, 46, 29, 45],
       [38, 17, 20, 49, 48],
       [19, 28, 17, 49, 25],
       [10, 22, 27, 21, 25],
       [43, 39, 34, 46, 29]])

In [82]:
df

VAL1 VAL2 VAL3 VAL4 VAL5
A   41   21   27   16   33
B   21   19   23   14   38
C   10   15   22   39   29
D   18   39   44   18   29
E   20   22   41   33   10
F   19   18   46   29   45
G   38   17   20   49   48
H   19   28   17   49   25
I   10   22   27   21   25
J   43   39   34   46   29

In [87]:
# LOC : * it is used to select elements from the Data Frame
# * it allows as to operate with the index's name
# * And with in the loc method, the first and last elements are included in the slicing.

In [92]:
df.loc["A":"D"]

VAL1 VAL2 VAL3 VAL4 VAL5
A   41   21   27   16   33
B   21   19   23   14   38
C   10   15   22   39   29
D   18   39   44   18   29

In [97]:
# ILOC method 
df.iloc[0,3]

16

In [119]:
df.iloc[0:4]

VAL1 VAL2 VAL3 VAL4 VAL5
A   41   21   27   16   33
B   21   19   23   14   38
C   10   15   22   39   29
D   18   39   44   18   29

In [103]:
df

VAL1 VAL2 VAL3 VAL4 VAL5
A   41   21   27   16   33
B   21   19   23   14   38
C   10   15   22   39   29
D   18   39   44   18   29
E   20   22   41   33   10
F   19   18   46   29   45
G   38   17   20   49   48
H   19   28   17   49   25
I   10   22   27   21   25
J   43   39   34   46   29

In [104]:
df.loc["C","VAL4"]

VAL4    39
Name: C, dtype: int32

In [108]:
# 4. Top Level Element Selection in Pandas DataFramesLesson 2
import numpy as np
import pandas as pd

In [109]:
np.random.seed(101)
array=np.random.randint(10,50,(10,5))
df=pd.DataFrame(data=array,index="A B C D E F G H I J".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [111]:
df

VAL1 VAL2 VAL3 VAL4 VAL5
A   41   21   27   16   33
B   21   19   23   14   38
C   10   15   22   39   29
D   18   39   44   18   29
E   20   22   41   33   10
F   19   18   46   29   45
G   38   17   20   49   48
H   19   28   17   49   25
I   10   22   27   21   25
J   43   39   34   46   29

In [116]:
df[["VAL3"]]["C":"G"]

VAL3
C   22
D   44
E   41
F   46
G   20

In [147]:
df.loc["C":"G","VAL3"] 

VAL3
C   22
D   44
E   41
F   46
G   20

In [149]:
df.loc["C":"G",["VAL3"]] 

VAL3
C   22
D   44
E   41
F   46
G   20

In [150]:
df.loc["C":"G"]

VAL1 VAL2 VAL3 VAL4 VAL5
C   10   15   22   39   29
D   18   39   44   18   29
E   20   22   41   33   10
F   19   18   46   29   45
G   38   17   20   49   48

In [152]:
df.loc["C":"G"][["VAL3"]]

VAL3
C   22
D   44
E   41
F   46
G   20

In [158]:
df.iloc[2:7,2]

C    22
D    44
E    41
F    46
G    20
Name: (VAL3,), dtype: int32

In [159]:
df.iloc[2:7,[2]]

VAL3
C   22
D   44
E   41
F   46
G   20

In [160]:
df.iloc[2:7][["VAL3"]]

VAL3
C   22
D   44
E   41
F   46
G   20

In [187]:
df.loc["C":"D"][['VAL2']]

VAL2
C   15
D   39

In [164]:
# 5. Top Level Element Selection in Pandas DataFramesLesson 3
import numpy as np
import pandas as pd

In [165]:
np.random.seed(101)
array=np.random.randint(10,50,(10,5))
df=pd.DataFrame(data=array,index="A B C D E F G H I J".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [185]:
df.loc["C":"H","VAL1":"VAL5"]

VAL1 VAL2 VAL3 VAL4 VAL5
C   10   15   22   39   29
D   18   39   44   18   29
E   20   22   41   33   10
F   19   18   46   29   45
G   38   17   20   49   48
H   19   28   17   49   25

In [195]:
df.iloc[2:8,1:4]

VAL2 VAL3 VAL4
C   15   22   39
D   39   44   18
E   22   41   33
F   18   46   29
G   17   20   49
H   28   17   49

In [180]:
df[["VAL1","VAL2","VAL3","VAL4"]][2:7]

VAL1 VAL2 VAL3 VAL4
C   10   15   22   39
D   18   39   44   18
E   20   22   41   33
F   19   18   46   29
G   38   17   20   49

In [182]:
df["VAL1"][0:3]

VAL1
A   41
B   21
C   10

In [200]:
df.iloc[2:8,1:4].loc["E":"F",["VAL3"]]

VAL3
E   41
F   46

In [233]:
# 6. Element Selection with Conditional Operations in
import numpy as np
import pandas as pd

In [236]:

array=np.random.randint(10,50,(10,5))
df=pd.DataFrame(data=array,index="A B C D E F G H I J".split(),columns=["VAL1 VAL2 VAL3 VAL4 VAL5".split()])

In [237]:
df

VAL1 VAL2 VAL3 VAL4 VAL5
A   45   40   20   49   30
B   37   18   32   36   33
C   47   32   19   12   28
D   38   21   20   40   45
E   38   13   29   30   24
F   15   15   16   34   49
G   47   17   47   14   33
H   45   25   44   13   28
I   23   13   47   39   32
J   31   31   27   33   40

In [204]:
df>20

VAL1   VAL2   VAL3   VAL4   VAL5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True
I  False   True   True   True   True
J   True   True   True   True   True

In [205]:
df == ""

VAL1   VAL2   VAL3   VAL4   VAL5
A  False  False  False  False  False
B  False  False  False  False  False
C  False  False  False  False  False
D  False  False  False  False  False
E  False  False  False  False  False
F  False  False  False  False  False
G  False  False  False  False  False
H  False  False  False  False  False
I  False  False  False  False  False
J  False  False  False  False  False

In [221]:
df == None

VAL1   VAL2   VAL3   VAL4   VAL5
A  False  False  False  False  False
B  False  False  False  False  False
C  False  False  False  False  False
D  False  False  False  False  False
E  False  False  False  False  False
F  False  False  False  False  False
G  False  False  False  False  False
H  False  False  False  False  False
I  False  False  False  False  False
J  False  False  False  False  False

In [222]:
df >20

VAL1   VAL2   VAL3   VAL4   VAL5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True
I  False   True   True   True   True
J   True   True   True   True   True

In [225]:
df[df >20]

VAL1  VAL2  VAL3  VAL4  VAL5
A  41.0  21.0  27.0   NaN  33.0
B  21.0   NaN  23.0   NaN  38.0
C   NaN   NaN  22.0  39.0  29.0
D   NaN  39.0  44.0   NaN  29.0
E   NaN  22.0  41.0  33.0   NaN
F   NaN   NaN  46.0  29.0  45.0
G  38.0   NaN   NaN  49.0  48.0
H   NaN  28.0   NaN  49.0  25.0
I   NaN  22.0  27.0  21.0  25.0
J  43.0  39.0  34.0  46.0  29.0

In [226]:
df["VAL1"]<20

VAL1
A  False
B  False
C   True
D   True
E  False
F   True
G  False
H   True
I   True
J  False

In [230]:
df[df["VAL1"]<20]

VAL1 VAL2 VAL3 VAL4 VAL5
A   NaN  NaN  NaN  NaN  NaN
B   NaN  NaN  NaN  NaN  NaN
C  10.0  NaN  NaN  NaN  NaN
D  18.0  NaN  NaN  NaN  NaN
E   NaN  NaN  NaN  NaN  NaN
F  19.0  NaN  NaN  NaN  NaN
G   NaN  NaN  NaN  NaN  NaN
H  19.0  NaN  NaN  NaN  NaN
I  10.0  NaN  NaN  NaN  NaN
J   NaN  NaN  NaN  NaN  NaN

In [232]:
df[df["VAL1"]<20][["VAL2"]]

VAL2
A  NaN
B  NaN
C  NaN
D  NaN
E  NaN
F  NaN
G  NaN
H  NaN
I  NaN
J  NaN

In [3]:
# 11. STRUCTURAL OPERATIONS ON PANDAS DATAFRAME
# 1. Adding Columns to Pandas Data Frames
import pandas as pd
import numpy as np

In [8]:
x=np.arange(0,28).reshape(7,4)
df=pd.DataFrame(data=x,columns='VAL1 VAL2 VAL3 VAL4'.split())

In [23]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6
0     0     1     2     3     1     5
1     4     5     6     7     9    13
2     8     9    10    11    17    21
3    12    13    14    15    25    29
4    16    17    18    19    33    37
5    20    21    22    23    41    45
6    24    25    26    27    49    53

In [24]:
df["VAL1"]+df["VAL2"]

0     1
1     9
2    17
3    25
4    33
5    41
6    49
dtype: int32

In [16]:
df["VAL5"]=df["VAL1"]+df["VAL2"]

In [17]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
0     0     1     2     3     1
1     4     5     6     7     9
2     8     9    10    11    17
3    12    13    14    15    25
4    16    17    18    19    33
5    20    21    22    23    41
6    24    25    26    27    49

In [33]:
df["VAL6"]=df["VAL3"] * df["VAL4"]

In [34]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6
0     0     1     2     3     1     6
1     4     5     6     7     9    42
2     8     9    10    11    17   110
3    12    13    14    15    25   210
4    16    17    18    19    33   342
5    20    21    22    23    41   506
6    24    25    26    27    49   702

In [43]:
df["VAL7"]=np.arange(28,35)

In [44]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7 VAL8
0     0     1     2     3     1     6    28   35
1     4     5     6     7     9    42    29   36
2     8     9    10    11    17   110    30   37
3    12    13    14    15    25   210    31   38
4    16    17    18    19    33   342    32   39
5    20    21    22    23    41   506    33   40
6    24    25    26    27    49   702    34

In [45]:
df["VAL8"]=[35,36,37,38,39,40,41]

In [46]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7  VAL8
0     0     1     2     3     1     6    28    35
1     4     5     6     7     9    42    29    36
2     8     9    10    11    17   110    30    37
3    12    13    14    15    25   210    31    38
4    16    17    18    19    33   342    32    39
5    20    21    22    23    41   506    33    40
6    24    25    26    27    49   702    34    41

In [42]:
df

VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7 VAL8
0     0     1     2     3     1     6    28   35
1     4     5     6     7     9    42    29   36
2     8     9    10    11    17   110    30   37
3    12    13    14    15    25   210    31   38
4    16    17    18    19    33   342    32   39
5    20    21    22    23    41   506    33   40
6    24    25    26    27    49   702    34

In [49]:
# 2. Removing Rows and Columns from Pandas Data frames
import numpy as np
import pandas as pd

In [65]:
x=np.arange(0,28).reshape(7,4)
df=pd.DataFrame(data=x,columns=["VAL1","VAL2","VAL3","VAL4"])

In [66]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [67]:
# removing columns 
df.drop(["VAL3","VAL4"],axis=1,inplace=False )

VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

In [68]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [69]:
# removing rows 
df.drop([2,5],axis=0,inplace=True)

In [70]:
df

VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
3    12    13    14    15
4    16    17    18    19
6    24    25    26    27

In [101]:
# 3. Null Values in Pandas Dataframes
import numpy as np
import pandas as pd

In [102]:
df=pd.DataFrame({'VAL1':[2,4,np.nan,6,np.nan,8,10],
                'VAL2':[123,np.nan,456,np.nan,789,246,357],
                'VAL3':['France','Greece','USA','Japan',"Sweden","Norway","Turkey"]})

In [103]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [117]:
df.isnull()

VAL1   VAL2   VAL3
0  False  False  False
1  False   True  False
2   True  False  False
3  False   True  False
4   True  False  False
5  False  False  False
6  False  False  False

In [118]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [119]:
df.isnull().sum()

VAL1    2
VAL2    2
VAL3    0
dtype: int64

In [121]:
len(df)

7

In [122]:
df.isnull().sum() /len(df)*100

VAL1    28.571429
VAL2    28.571429
VAL3     0.000000
dtype: float64

In [123]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [125]:
df.notnull()

VAL1   VAL2  VAL3
0   True   True  True
1   True  False  True
2  False   True  True
3   True  False  True
4  False   True  True
5   True   True  True
6   True   True  True

In [136]:
df.notnull().sum().sum()

17

In [137]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [135]:
df["VAL1"].notnull()

0     True
1     True
2    False
3     True
4    False
5     True
6     True
Name: VAL1, dtype: bool

In [134]:
df[df["VAL1"].notnull()]

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
3   6.0    NaN   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [142]:
df.isnull().any()

VAL1     True
VAL2     True
VAL3    False
dtype: bool

In [153]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [140]:
df.isnull().any(axis=1)

0    False
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [143]:
condition=df.isnull().any(axis=1)

In [145]:
df[condition]

VAL1   VAL2    VAL3
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden

In [154]:
df[~condition]

VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [158]:
df2=df

In [150]:
df.notnull().all()

VAL1    False
VAL2    False
VAL3     True
dtype: bool

In [157]:
df.notnull().any()

VAL1    True
VAL2    True
VAL3    True
dtype: bool

In [162]:
df=df2

In [165]:
df2["VAL1"]=[1,2,3,4,5,6,7]

In [166]:
df2

VAL1   VAL2    VAL3
0     1  123.0  France
1     2    NaN  Greece
2     3  456.0     USA
3     4    NaN   Japan
4     5  789.0  Sweden
5     6  246.0  Norway
6     7  357.0  Turkey

In [167]:
df2.notnull().any()

VAL1    True
VAL2    True
VAL3    True
dtype: bool

In [168]:
df2.notnull().all()

VAL1     True
VAL2    False
VAL3     True
dtype: bool

In [170]:
df2.notnull().all(axis=1)

0     True
1    False
2     True
3    False
4     True
5     True
6     True
dtype: bool

In [171]:
# 4. Dropping Null Values Dropna() Function
import numpy as np
import pandas as pd

In [172]:
df=pd.DataFrame({'VAL1':[2,4,np.nan,6,np.nan,8,10],
                'VAL2':[123,np.nan,456,np.nan,789,246,357],
                'VAL3':['France','Greece','USA','Japan',"Sweden","Norway","Turkey"]})