In [2]:
# PANDAS LIBRARY INTRODUCTION 
# introduction to pandas library
# works of pandas is : 
#     Data Analysis and Data Manipulation,
#     Collect and Transform Data
#     Reshaping of Data Sets 
#     Time series-specific Functionality
#     Converting Other data structures into DataFrame 

In [3]:
# SERIES STRUCTURE IN PANDAS LIBRARY
# Creating a Pandas Series with a List 
# the Pandas series; was created based on NumPy arrays 
# Pandas series keeps index information for each value as an extra.

In [4]:
import pandas as pd

In [14]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [20]:
list_data=[2,4,6,8,10]
list_index=["a","b","c","d","e"]

In [29]:
variable=pd.Series(data=list_data,index=list_index,dtype="float16")

In [30]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float16

In [31]:
type(variable)

pandas.core.series.Series

In [39]:
list_data=[2,4,6,8,10,12]
list_index=["a","b","c","d","e"]

In [37]:
pd.Series(list_data,list_index)

ValueError: Length of values (5) does not match length of index (6)

In [40]:
# 2. Creating a Pandas Series with a Dictionary
import pandas as pd

In [43]:
dictionary={"ferrari":334.7,"porche":337.9,"lamborghini":349}

In [52]:
for carSpeed,speed in dictionary.items():
    print(carSpeed,speed)

ferrari 334.7
porche 337.9
lamborghini 349


In [45]:
pd.Series(data=dictionary)

ferrari        334.7
porche         337.9
lamborghini    349.0
dtype: float64

In [54]:
pd.Series(data=dictionary,index=["porche","bugatti","ferrari"])

porche     337.9
bugatti      NaN
ferrari    334.7
dtype: float64

In [56]:
# 3. Creating Pandas Series with NumPy Array
import numpy as np
import pandas as pd

In [58]:
example=np.array([1,3.3,5,7.2,9])
labels=np.array(["a","b","c","d","e"])

In [60]:
numpyArrVariable=pd.Series(data=example,index=labels)

In [61]:
numpyArrVariable

a    1.0
b    3.3
c    5.0
d    7.2
e    9.0
dtype: float64

In [62]:
# 4. Object types in Series 
import pandas as pd

In [64]:
example=pd.Series(["world",100,5.8,False])

In [65]:
example

0    world
1      100
2      5.8
3    False
dtype: object

In [70]:
print(type(example[0]))
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [79]:
pd.Series([sum,type,max])

0    <built-in function sum>
1             <class 'type'>
2    <built-in function max>
dtype: object

In [80]:
# 5. Examining the Primary Features of the Pandas Seri
import pandas as pd

In [81]:
example=pd.Series([10,20,30,40,50,60,70])

In [82]:
example

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [84]:
example.axes

[RangeIndex(start=0, stop=7, step=1)]

In [85]:
example.dtype

dtype('int64')

In [87]:
example.ndim

1

In [94]:
example.head(4) # head method return first five values by default

0    10
1    20
2    30
3    40
dtype: int64

In [96]:
example.tail(3)

4    50
5    60
6    70
dtype: int64

In [97]:
# 6. Most Applied Methods on Pandas Series
import pandas as pd

In [103]:
variable2=pd.Series([8,3,6,5,1],index=["a","b","c","d","e"])

In [104]:
variable2

a    8
b    3
c    6
d    5
e    1
dtype: int64

In [105]:
new_variable=variable2.sort_index()

In [106]:
new_variable

a    8
b    3
c    6
d    5
e    1
dtype: int64

In [112]:
new_variable2=variable2.sort_values()

In [113]:
new_variable2

e    1
b    3
d    5
c    6
a    8
dtype: int64

In [115]:
variable2.isin([6,1])

a    False
b    False
c     True
d    False
e     True
dtype: bool

In [116]:
variable2[variable2.isin([6,1])]

c    6
e    1
dtype: int64

In [119]:
variable2.values

array([8, 3, 6, 5, 1], dtype=int64)

In [120]:
variable2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [122]:
[i for i in variable2.values]

[8, 3, 6, 5, 1]

In [123]:
variable2.items

<bound method Series.items of a    8
b    3
c    6
d    5
e    1
dtype: int64>

In [124]:
variable2.items()

In [125]:
list(variable2.items())

[('a', 8), ('b', 3), ('c', 6), ('d', 5), ('e', 1)]

In [130]:
for index,value in variable2.items():
    print(index, '-', value)

a - 8
b - 3
c - 6
d - 5
e - 1


In [131]:
# 7. Indexing and Slicing Pandas Series
import pandas as pd

In [132]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [133]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [135]:
example[2:6]

France    +33
Italy     +39
Sweden    +46
Norway    +47
dtype: object

In [137]:
example[0::2]

Turkey    +90
France    +33
Sweden    +46
dtype: object

In [138]:
example["Germany"]

'+49'

In [144]:
example["France":"Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [ ]:
# 9. DataFrame Structures in Pandas Library
# 1. Creating Pandas DataFrame with List 
# Pandas Dataframe is a multidimensional data structure 

In [145]:
import pandas as pd

In [155]:
list_example=[5,10,15,20,25]

In [156]:
pd.DataFrame(data=list_example,columns=["values"],dtype="float")

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

In [ ]:
# 2. Creating Pandas DataFrame with NumPy Array

In [158]:
import numpy as np
import pandas as pd

In [159]:
array_example=np.random.randint(0,50,(4,4))

In [160]:
array_example

array([[33, 22, 43, 32],
       [39, 28, 39, 31],
       [29, 17,  5, 41],
       [46,  3, 37,  7]])

In [164]:
df=pd.DataFrame(array_example,index=["row1","row2","row3","row4"],columns=["col1","col2","col3","col4"])

In [165]:
df

col1  col2  col3  col4
row1    33    22    43    32
row2    39    28    39    31
row3    29    17     5    41
row4    46     3    37     7

In [166]:
# 3. Creating Pandas DataFrame with Dictionary 
import numpy as np
import pandas as pd

In [179]:
x=np.random.randint(10,50,size=6)
y=np.random.randint(10,50,size=6)
z=np.random.randint(10,50,size=6)
t=np.random.randint(10,50,size=6)

In [174]:
x

array([29, 12, 20, 44, 40, 34])

In [175]:
y

array([24, 35, 22, 30, 33, 39])

In [176]:
z

array([31, 49, 49, 27, 48, 42])

In [185]:
dict_example={"val1":x,"val2":y,"val3":z,"val4":t}

In [186]:
dict_example

{'val1': array([33, 43, 38, 15, 45, 10]),
 'val2': array([14, 26, 21, 15, 15, 25]),
 'val3': array([49, 28, 16, 12, 23, 17]),
 'val4': array([28, 45, 37, 36, 45, 15])}

In [187]:
df=pd.DataFrame(dict_example)

In [188]:
df

val1  val2  val3  val4
0    33    14    49    28
1    43    26    28    45
2    38    21    16    37
3    15    15    12    36
4    45    15    23    45
5    10    25    17    15

In [184]:
# 4. Examining the Properties of Pandas DataFrames
import numpy as np
import pandas as pd
x1=np.random.randint(10,50,size=6)
y1=np.random.randint(10,50,size=6)
z1=np.random.randint(10,50,size=6)
t1=np.random.randint(10,50,size=6)

In [189]:
df.head() # it gives df variable DataFrame first five values by default 

val1  val2  val3  val4
0    33    14    49    28
1    43    26    28    45
2    38    21    16    37
3    15    15    12    36
4    45    15    23    45

In [190]:
df.head(3)

val1  val2  val3  val4
0    33    14    49    28
1    43    26    28    45
2    38    21    16    37

In [192]:
df.tail(3) # gives last three dataFrames rows 

val1  val2  val3  val4
3    15    15    12    36
4    45    15    23    45
5    10    25    17    15

In [193]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [196]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [198]:
df.columns=["new1","new2","new3","new4"]

In [199]:
df

new1  new2  new3  new4
0    33    14    49    28
1    43    26    28    45
2    38    21    16    37
3    15    15    12    36
4    45    15    23    45
5    10    25    17    15

In [200]:
df.values

array([[33, 14, 49, 28],
       [43, 26, 28, 45],
       [38, 21, 16, 37],
       [15, 15, 12, 36],
       [45, 15, 23, 45],
       [10, 25, 17, 15]])

In [201]:
type(df.values)

numpy.ndarray

In [202]:
type(df)

pandas.core.frame.DataFrame

In [203]:
df.describe()

new1       new2       new3       new4
count   6.000000   6.000000   6.000000   6.000000
mean   30.666667  19.333333  24.166667  34.333333
std    14.760307   5.391351  13.407709  11.413442
min    10.000000  14.000000  12.000000  15.000000
25%    19.500000  15.000000  16.250000  30.000000
50%    35.500000  18.000000  20.000000  36.500000
75%    41.750000  24.000000  26.750000  43.000000
max    45.000000  26.000000  49.000000  45.000000

In [204]:
df.ndim

2

In [205]:
df.shape

(6, 4)

In [206]:
df.size

24

In [211]:
# ELEMENT SELECTION OPERATIONS IN DATAFRAME STRUCTURES
# 1. Element Selection Operations in Pandas DataFrames Lesson 1 
import numpy as np
import pandas as pd