In [2]:
# INTRODUCTION TO NUMPY LIBRARY 
'''
1) Numpy is a library that allows us to perform large-scale mathematical-scientific
calculations efficiently, quickly and flexiblity.

2) It is considered indispensable, especially for Data Science studies and includes related solutions.

NUMPY Mainly used in DATA MNINING, MACHINE LEARNING, DATA ANALYSIS, COMPUTATIONAL STRUCTURES
'''


'\n1) Numpy is a library that allows us to perform large-scale mathematical-scientific\ncalculations efficiently, quickly and flexiblity.\n\n2) It is considered indispensable, especially for Data Science studies and includes related solutions.\n\nNUMPY Mainly used in DATA MNINING, MACHINE LEARNING, DATA ANALYSIS, COMPUTATIONAL STRUCTURES\n'

In [2]:
# THE POWER OF NUMPY
list(range(0,5))

[0, 1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
x=np.array([1,3,5,7,9])

In [5]:
y=np.array([2,4,6,8,10])

In [6]:
x+y

array([ 3,  7, 11, 15, 19])

In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
x*y

array([ 2, 12, 30, 56, 90])

In [9]:
array=np.array(['ali',2,2,4,5])

In [10]:
array

array(['ali', '2', '2', '4', '5'], dtype='<U11')

In [11]:
new_variable2=np.array([5.8,9,7,5],dtype="int")

In [13]:
new_variable2

array([5, 9, 7, 5])

In [21]:
# Create a numpy array with the zeros() function 
np.zeros((3,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# Create a numpy array with the ones() function 
np.ones((3,4,5),dtype="int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [27]:
# Create a numpy array with the full() function
np.full((3,5),2,dtype="int")

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [31]:
# Create a numpy Array with the arange() function
# syntax: arange(start,stop,step,dtype)
np.arange(1,20,2,dtype="int")

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# Create a numpy Array with the Eye() function
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
np.eye(3,3,dtype="bool")

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
# Create a numpy Array with the Linspace() function
np.linspace(10,30,num=10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [23]:
# Create a numpy array using random function 
np.random.rand(6)

array([0.14469544, 0.91035824, 0.84136403, 0.89912889, 0.81388803,
       0.11621026])

In [56]:
np.random.rand(2,3)

array([[0.61104117, 0.48549225, 0.59645558],
       [0.2910197 , 0.49687775, 0.63888137]])

In [43]:
# Create a numpy array using random function 
np.random.randn(5)

array([ 0.87936069, -1.49665716,  0.18548082,  0.8922081 ,  2.12984055])

In [58]:
# parameters(mean,standard deviation, (tupple of rows and cols))
np.random.normal(20,5,(4,3))

array([[17.55142036, 22.59438902, 21.20136929],
       [26.42327153,  9.68375859, 25.55961463],
       [25.52269254, 26.90312514, 26.14515775],
       [19.42085774, 15.37932363, 15.55880619]])

In [69]:
np.random.randint(0,10,(4,4))

array([[1, 9, 3, 3],
       [6, 8, 8, 3],
       [8, 8, 9, 3],
       [0, 0, 7, 2]])

In [67]:
# Properties of NumpyArray 
# ndim:- it gives us information about the number of the sizr of the array .
# shape:- Shape function allows us to learn the size of the information of the array.
# size:- This function gives us the total number of elements of the array.
# dtype:- This function return the data type of the NumPy array. 

In [87]:
matrix=np.random.randint(10,50,(5,4),dtype="int64")

In [88]:
matrix

array([[21, 42, 32, 36],
       [30, 35, 35, 34],
       [34, 16, 39, 32],
       [30, 23, 46, 31],
       [16, 19, 18, 11]], dtype=int64)

In [89]:
matrix.ndim

2

In [90]:
matrix.shape

(5, 4)

In [91]:
matrix.size

20

In [93]:
matrix.dtype

dtype('int64')

In [94]:
# FUNCTIONS IN NUMPY LIBRARY 
# Reshapping the numpy array Reshape() function 

import numpy as np

In [97]:
example=np.arange(1,16)

In [98]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [118]:
example.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [102]:
array=example.reshape((1,15))

In [103]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [104]:
array.ndim

2

In [117]:
example.reshape((4,3))

ValueError: cannot reshape array of size 15 into shape (4,3)

In [121]:
newExample=example.reshape((3,5))

In [125]:
for index in newExample.data:
    print(index)

NotImplementedError: multi-dimensional sub-views are not implemented

In [ ]:
# Identify the largest Element of a Numpy Array 
# max():- The max() function returns us the largest element in an array
# argmax():- The argmax() function returns the index number of the largest element in array. 

In [139]:
array=np.random.randint(0,50,10)

In [140]:
array

array([29, 27,  4, 32,  6, 35, 49, 15, 12, 32])

In [141]:
array.max() # Gives maximum value from the array

49

In [142]:
array.argmax() #Gives maximum value index from the array

6

In [150]:
array2=np.random.randint(0,50,(4,3)) 

In [151]:
array2

array([[16, 34, 43],
       [26, 41, 37],
       [17, 20,  5],
       [43, 24, 19]])

In [152]:
array2.argmax()

2

In [155]:
# Detecting Least Element of Numpy Array 
import numpy as np

In [156]:
arr=np.random.randint(20,70,10)

In [157]:
arr

array([25, 57, 48, 63, 62, 35, 39, 31, 41, 60])

In [158]:
arr.min()

25

In [159]:
arr.argmin()

0

In [160]:
arr2=np.random.randint(20,70,(5,3))

In [161]:
arr2

array([[45, 50, 48],
       [63, 54, 62],
       [33, 26, 54],
       [68, 62, 20],
       [32, 25, 40]])

In [162]:
arr2.min()

20

In [163]:
arr2.argmin()

11

In [164]:
# Concatenating Numpy Arrays Concatenate() Function 
import numpy as np

In [166]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])

In [173]:
np.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [174]:
# Splitting one dimmensional Arrays The Split function 
import numpy as np

In [175]:
array=np.array([1,3,5,50,50,2,4,6])

In [180]:
np.split(array,[3,5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [182]:
x,y,z=np.split(array,[3,5])

In [185]:
x

array([1, 3, 5])

In [186]:
y

array([50, 50])

In [187]:
z

array([2, 4, 6])

In [188]:
np.split(array,4) # not this method divides the array into 4 equal parts 

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [45]:
# Splitting two dimmensional Arrays The Split function 
array=np.arange(20).reshape(5,4)

In [46]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
np.split(array,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [208]:
x,y,z=np.split(array,[1,4])

In [209]:
x

array([[0, 1, 2, 3]])

In [210]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
z

array([[16, 17, 18, 19]])

In [216]:
np.split(array,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [217]:
# hsplit function in numpy 
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [218]:
np.hsplit(array,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [220]:
np.hsplit(array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [222]:
# vsplit function in numpy library
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [225]:
np.vsplit(array,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [226]:
np.vsplit(array,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [228]:
# Sorting Numpy Arrays Sort() Function 
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [234]:
variable=np.array([3,5,1,8,6,2,9])

In [236]:
np.sort(variable)

array([1, 2, 3, 5, 6, 8, 9])

In [238]:
variable2=np.sort(variable)

In [239]:
variable2

array([1, 2, 3, 5, 6, 8, 9])

In [58]:
example=np.random.normal(30,10,(4,4))

In [59]:
example

array([[28.12780595, 15.07128181, 39.01221147, 26.94693811],
       [40.00221239, 45.89660408, 45.65551493, 27.34075161],
       [22.11243971, 32.58426235, 18.97739841, 30.85203973],
       [49.85352155, 18.80374422, 22.1162109 , 35.63765385]])

In [60]:
np.sort(example)

array([[15.07128181, 26.94693811, 28.12780595, 39.01221147],
       [27.34075161, 40.00221239, 45.65551493, 45.89660408],
       [18.97739841, 22.11243971, 30.85203973, 32.58426235],
       [18.80374422, 22.1162109 , 35.63765385, 49.85352155]])

In [61]:
np.sort(example,axis=0)

array([[22.11243971, 15.07128181, 18.97739841, 26.94693811],
       [28.12780595, 18.80374422, 22.1162109 , 27.34075161],
       [40.00221239, 32.58426235, 39.01221147, 30.85203973],
       [49.85352155, 45.89660408, 45.65551493, 35.63765385]])

In [57]:
np.sort(example,axis=1)


array([[15.71324121, 32.16425668, 38.15537394, 48.04580834],
       [29.46432887, 36.73114517, 36.88588633, 50.66161376],
       [21.09248886, 23.89967339, 31.6957932 , 40.45439114],
       [21.22753654, 28.93235074, 33.18924579, 41.98202547]])

In [2]:
# 5. Indexing, Slicing, and Assigning NumPy Arrays 
# Indexing Numpy Arrays 
import numpy as np
array=np.arange(0,11)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
array[4]

4

In [7]:
array[-1]

10

In [11]:
array[2:7:2]

array([2, 4, 6])

In [17]:
variable=np.array([[5,10,15],
                  [20,25,30],
                  [35,40,45]])

In [18]:
variable

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
variable[1]

array([20, 25, 30])

In [23]:
variable[0,0]

5

In [26]:
variable[2,1]

40

In [27]:
variable[-1,-3]

35

In [30]:
# Slicing One dimensional Numpy Arrays
example=np.arange(10,20)

In [31]:
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
example[2:6]

array([12, 13, 14, 15])

In [36]:
example[3::2]

array([13, 15, 17, 19])

In [37]:
example[:7:3]

array([10, 13, 16])

In [45]:
# Slicing Two-Dimensional Numpy Arrays 
array=np.arange(30).reshape(6,5)

In [46]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [47]:
array[2,:]

array([10, 11, 12, 13, 14])

In [48]:
array[2]

array([10, 11, 12, 13, 14])

In [50]:
array[:, 2]

array([ 2,  7, 12, 17, 22, 27])

In [51]:
array[:, 0]

array([ 0,  5, 10, 15, 20, 25])

In [52]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [54]:
array[1:4,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [55]:
array[0::2,0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [56]:
# Assigning Values to One dimensional array
variable=np.array([0,1,2,3,7,5,6,9,8,9])

In [57]:
variable

array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [63]:
variable[7]=7

In [64]:
variable

array([0, 1, 2, 3, 7, 5, 6, 7, 8, 9])

In [65]:
new_variable=variable[5:]

In [67]:
variable[5:]=20,30,40,50,60

In [68]:
variable

array([ 0,  1,  2,  3,  7, 20, 30, 40, 50, 60])

In [102]:
# Assigning Value to Two Dimensional Array 
example=np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])

In [103]:
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [104]:
example[1,1]=100

In [105]:
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [106]:
example[1,0]=100.6

In [107]:
example

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [108]:
example[:,2]=100

In [109]:
example

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [110]:
example[0::2,0:2]

array([[10, 20],
       [70, 80]])

In [128]:
example[0::2,0:2]=100

In [129]:
example

array([[100, 100,  30],
       [ 20, 100, 100],
       [100, 100, 100]])

In [126]:
example[0]=10,20,30

In [127]:
example

array([[ 10,  20,  30],
       [ 20, 100, 100],
       [ 30, 100, 100]])

In [122]:
example[:,0]=10,20,30

In [130]:
example

array([[100, 100,  30],
       [ 20, 100, 100],
       [100, 100, 100]])

In [131]:
# Fancy Indexing of One-Dimensional Array 
import numpy as np

In [132]:
fancy=np.arange(0,50,5)

In [134]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [139]:
[fancy[1],fancy[3],fancy[5]]

[5, 15, 25]

In [140]:
 indexes=[1,3,5]

In [142]:
fancy[indexes]

array([ 5, 15, 25])

In [143]:
array=np.array([1,3,5])

In [144]:
array

array([1, 3, 5])

In [145]:
fancy[array]

array([ 5, 15, 25])

In [146]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
# Fancy indexing of Two-Dimensional Arrays 
import numpy as np
variable=np.zeros((10,10),dtype="int")

In [12]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
variable.shape

(10, 10)

In [19]:
row=variable.shape[0]
cols=variable.shape[1]

In [21]:
row

10

In [22]:
cols

10

In [171]:
for i in range(row):
    variable[i]=i

In [172]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [173]:
list1=[1,3,5,7]

In [174]:
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [175]:
list2=[8,5,2,7,3]

In [176]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [177]:
example=np.arange(1,17).reshape((4,4))

In [178]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [200]:
example[[0,3],[1,2]]

array([ 2, 15])

In [199]:
example[[0,3],[2,1]]

array([ 3, 14])

In [201]:
# 7,10 indexing 
example[[1,2],[2,1]]

array([ 7, 10])

In [202]:
# 3,12 indexing 
example[[0,2],[2,3]]

array([ 3, 12])

In [203]:
#  9,6,15,4 indexing 
example[[2,1,3,0],[0,1,2,3]]

array([ 9,  6, 15,  4])

In [205]:
row=[0,2,3,1]
column=[3,0,2,1]


example[row,column]

array([ 4,  9, 15,  6])

In [4]:
import numpy as np

In [5]:
newarray=np.array([5,6,7,8,9])

In [7]:
indexes=[2,3,4]

In [8]:
newarray[indexes]

array([7, 8, 9])

In [63]:
# Combining FFancy index with Normal Indexing 
import numpy as np

In [64]:
example=np.arange(1,17).reshape((4,4))

In [65]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
example[1,[1,3]]

array([6, 8])

In [69]:
example[2,[0,2]]

array([ 9, 11])

In [70]:
example[[0,1],2]

array([3, 7])

In [71]:
# Cobining Fancy indexing with Normal slicing 
import numpy as np

In [72]:
example=np.arange(1,17).reshape((4,4))

In [73]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [80]:
example[0:,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [76]:
example[[0,3],0:]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [82]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [83]:
example[[1,2],1:3]

array([[ 6,  7],
       [10, 11]])

In [91]:
# OPERATIONS IN NUMPY LIBRARY
# Operations with comparison Operators 
import numpy as np

In [92]:
array=np.arange(1,11)

In [93]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
array >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [97]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [98]:
condition=array <=4

In [99]:
condition

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [102]:
array[condition]

array([1, 2, 3, 4])

In [109]:
new_condition=(array != 8) & (array>=6)

In [110]:
new_condition 

array([False, False, False, False, False,  True,  True, False,  True,
        True])

In [106]:
array[new_condition]

array([ 6,  7,  9, 10])

In [85]:
a=np.array([[1,2,3],
           [4,5,6]])

In [86]:
b=np.array([[1,2,3],
           [4,5,6]])

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [111]:
a==b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [2]:
# Operations with Arithematic Operators in Python 
import numpy as np

In [3]:
array=np.arange(1,11)

In [4]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
((array *10)+20)/5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [9]:
array*array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
 array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
np.multiply(array,array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
np.subtract(array,2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [18]:
np.add(array,20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [19]:
np.divide(array,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
# exponents 
array ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [24]:
np.power(array,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [25]:
np.sqrt(4)

2.0

In [27]:
np.sqrt(100)

10.0

In [28]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [29]:
np.mod(array,5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [32]:
# trignometry expression operations in numpy 
np.sin(180)

-0.8011526357338304

In [33]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [34]:
np.cos(180)

-0.5984600690578582

In [35]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [36]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [40]:
# What are ufunc in numpy :-Functions that operate element by element on whole arrays.
# np.info(np.ufunc)

In [41]:
# Statistical Operations in Numpy 
import numpy as np

In [43]:
array2=np.arange(1,11)

In [44]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.sum(array2)

55

In [46]:
np.mean(array2)

5.5

In [52]:
np.median(array2)

5.5

In [55]:
np.min(array2)

1

In [54]:
np.max(array2)

10

In [57]:
np.std(array2)  #Standard Deviation of an array

2.8722813232690143

In [62]:
np.var(array2) # variance is the square of standard deviation

8.25

In [60]:
np.sqrt(np.var(array))

2.8722813232690143

In [71]:
# Solving Second Degree Equations using NumPy library
import numpy as np

In [75]:
# Equations which we have to solve 
# 2X1 + X2 = 5
# -3X1 + 6X2 = 0

In [77]:
coefficient=np.array([[2,1],[-3,6]])

In [78]:
coefficient

array([[ 2,  1],
       [-3,  6]])

In [79]:
output=np.array([5,0])

In [80]:
output

array([5, 0])

In [82]:
np.linalg.solve(coefficient,output)

array([2., 1.])

In [83]:
# The end of Numpy Library 

In [94]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])