In [2]:
# INTRODUCTION TO NUMPY LIBRARY 
'''
1) Numpy is a library that allows us to perform large-scale mathematical-scientific
calculations efficiently, quickly and flexiblity.

2) It is considered indispensable, especially for Data Science studies and includes related solutions.

NUMPY Mainly used in DATA MNINING, MACHINE LEARNING, DATA ANALYSIS, COMPUTATIONAL STRUCTURES
'''


'\n1) Numpy is a library that allows us to perform large-scale mathematical-scientific\ncalculations efficiently, quickly and flexiblity.\n\n2) It is considered indispensable, especially for Data Science studies and includes related solutions.\n\nNUMPY Mainly used in DATA MNINING, MACHINE LEARNING, DATA ANALYSIS, COMPUTATIONAL STRUCTURES\n'

In [2]:
# THE POWER OF NUMPY
list(range(0,5))

[0, 1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
x=np.array([1,3,5,7,9])

In [5]:
y=np.array([2,4,6,8,10])

In [6]:
x+y

array([ 3,  7, 11, 15, 19])

In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
x*y

array([ 2, 12, 30, 56, 90])

In [9]:
array=np.array(['ali',2,2,4,5])

In [10]:
array

array(['ali', '2', '2', '4', '5'], dtype='<U11')

In [11]:
new_variable2=np.array([5.8,9,7,5],dtype="int")

In [13]:
new_variable2

array([5, 9, 7, 5])

In [21]:
# Create a numpy array with the zeros() function 
np.zeros((3,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# Create a numpy array with the ones() function 
np.ones((3,4,5),dtype="int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [27]:
# Create a numpy array with the full() function
np.full((3,5),2,dtype="int")

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [31]:
# Create a numpy Array with the arange() function
# syntax: arange(start,stop,step,dtype)
np.arange(1,20,2,dtype="int")

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# Create a numpy Array with the Eye() function
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
np.eye(3,3,dtype="bool")

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
# Create a numpy Array with the Linspace() function
np.linspace(10,30,num=10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [55]:
# Create a numpy array using random function 
np.random.rand(5)

array([0.56025002, 0.87723095, 0.55500519, 0.53689835, 0.90956938])

In [56]:
np.random.rand(2,3)

array([[0.61104117, 0.48549225, 0.59645558],
       [0.2910197 , 0.49687775, 0.63888137]])

In [54]:
# Create a numpy array using random function 
np.random.randn(5)

array([-1.33399283, -1.39744795, -2.10124336,  0.95946674,  0.20239351])

In [58]:
# parameters(mean,standard deviation, (tupple of rows and cols))
np.random.normal(20,5,(4,3))

array([[17.55142036, 22.59438902, 21.20136929],
       [26.42327153,  9.68375859, 25.55961463],
       [25.52269254, 26.90312514, 26.14515775],
       [19.42085774, 15.37932363, 15.55880619]])

In [69]:
np.random.randint(0,10,(4,4))

array([[1, 9, 3, 3],
       [6, 8, 8, 3],
       [8, 8, 9, 3],
       [0, 0, 7, 2]])

In [67]:
# Properties of NumpyArray 
# ndim:- it gives us information about the number of the sizr of the array .
# shape:- Shape function allows us to learn the size of the information of the array.
# size:- This function gives us the total number of elements of the array.
# dtype:- This function return the data type of the NumPy array. 

In [87]:
matrix=np.random.randint(10,50,(5,4),dtype="int64")

In [88]:
matrix

array([[21, 42, 32, 36],
       [30, 35, 35, 34],
       [34, 16, 39, 32],
       [30, 23, 46, 31],
       [16, 19, 18, 11]], dtype=int64)

In [89]:
matrix.ndim

2

In [90]:
matrix.shape

(5, 4)

In [91]:
matrix.size

20

In [93]:
matrix.dtype

dtype('int64')

In [94]:
# FUNCTIONS IN NUMPY LIBRARY 
# Reshapping the numpy array Reshape() function 

import numpy as np

In [97]:
example=np.arange(1,16)

In [98]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [118]:
example.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [102]:
array=example.reshape((1,15))

In [103]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [104]:
array.ndim

2

In [117]:
example.reshape((4,3))

ValueError: cannot reshape array of size 15 into shape (4,3)

In [121]:
newExample=example.reshape((3,5))

In [125]:
for index in newExample.data:
    print(index)

NotImplementedError: multi-dimensional sub-views are not implemented

In [ ]:
# Identify the largest Element of a Numpy Array 
# max():- The max() function returns us the largest element in an array
# argmax():- The argmax() function returns the index number of the largest element in array. 

In [139]:
array=np.random.randint(0,50,10)

In [140]:
array

array([29, 27,  4, 32,  6, 35, 49, 15, 12, 32])

In [141]:
array.max() # Gives maximum value from the array

49

In [142]:
array.argmax() #Gives maximum value index from the array

6

In [150]:
array2=np.random.randint(0,50,(4,3)) 

In [151]:
array2

array([[16, 34, 43],
       [26, 41, 37],
       [17, 20,  5],
       [43, 24, 19]])

In [152]:
array2.argmax()

2

In [155]:
# Detecting Least Element of Numpy Array 
import numpy as np

In [156]:
arr=np.random.randint(20,70,10)

In [157]:
arr

array([25, 57, 48, 63, 62, 35, 39, 31, 41, 60])

In [158]:
arr.min()

25

In [159]:
arr.argmin()

0

In [160]:
arr2=np.random.randint(20,70,(5,3))

In [161]:
arr2

array([[45, 50, 48],
       [63, 54, 62],
       [33, 26, 54],
       [68, 62, 20],
       [32, 25, 40]])

In [162]:
arr2.min()

20

In [163]:
arr2.argmin()

11

In [164]:
# Concatenating Numpy Arrays Concatenate() Function 
import numpy as np

In [166]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])

In [173]:
np.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [174]:
# Splitting one dimmensional Arrays The Split function 
import numpy as np

In [175]:
array=np.array([1,3,5,50,50,2,4,6])

In [180]:
np.split(array,[3,5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [182]:
x,y,z=np.split(array,[3,5])

In [185]:
x

array([1, 3, 5])

In [186]:
y

array([50, 50])

In [187]:
z

array([2, 4, 6])

In [188]:
np.split(array,4) # not this method divides the array into 4 equal parts 

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [200]:
# Splitting two dimmensional Arrays The Split function 
array=np.arange(20).reshape(5,4)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [201]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [203]:
np.split(array,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [208]:
x,y,z=np.split(array,[1,4])

In [209]:
x

array([[0, 1, 2, 3]])

In [210]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
z

array([[16, 17, 18, 19]])

In [216]:
np.split(array,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [217]:
# hsplit function in numpy 
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [218]:
np.hsplit(array,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [220]:
np.hsplit(array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [222]:
# vsplit function in numpy library
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [225]:
np.vsplit(array,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [226]:
np.vsplit(array,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [227]:
# Sorting Numpy Arrays Sort() Function 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])